stages:
  data_ingestion_and_processing:
    cmd: python src/data_processing.py
    deps:
    - src/data_ingestion.py   
    - src/data_processing.py 
    - raw_data/personality_dataset.csv
    outs: 
      - data/processed/processed_personality.csv

  data_splitting:
    cmd: python src/splitting_data.py  
    deps: 
    -  src/splitting_data.py
    - data/processed/processed_personality.csv 
    outs:
    - data/train_test/train.csv
    - data/train_test/test.csv
  model:
    cmd: python src/model.py  
    deps: 
      - data/train_test/train.csv
      - data/train_test/test.csv 
      - src/model.py 
    outs:
      - models/personality_model.pkl 
      - models/report/personality_model_report.txt
    