stages:
  data_ingestion_and_processing:
    cmd: python src/data_processing.py
    deps:
    - src/data_ingestion.py   
    - src/data_processing.py 
    - raw_data/personality_dataset.csv
    outs: 
      - data/processed/processed_personality.csv

    